### PR TITLE
fix(windows): keep tray window alive when initial registration fails

### LINKED ISSUE #171: Using windows task scheduler to start app, sometimes an error occurs
I need the app to run as admin by default when autostart, so I use [task scheduler](https://learn.microsoft.com/en-us/windows/win32/taskschd/task-scheduler-start-page) to do this
But sometimes an error message appears
`
Tray(OsError(Os { code: -2147467259, kind: Uncategorized, message: "未指定的错误" }))
`
﻿
```
builder
  .setup(|app| {
    let result = TrayIconBuilder::with_id("tray")
           .icon(app.default_window_icon().unwrap().clone())
           .build(app);
  })
```

```
name = "tray-icon"
version = "0.13.4"
```

### PR DESCRIPTION
**Pull request by Slinetrac**
Closes #171.

Handle Windows tray icon creation when the taskbar is not ready by keeping the message window alive and re-registering on TaskbarCreated.

Tested with examples and works as expected.

### CODE REVIEW

File: src/platform_impl/windows/mod.rs [hunk 1]
```diff
@@ -117,19 +121,29 @@ impl TrayIcon {
...
             let hicon = attrs.icon.as_ref().map(|i| i.inner.as_raw_handle());
 
-            if !register_tray_icon(hwnd, internal_id, &hicon, &attrs.tooltip) {
-                let result = Err(crate::Error::OsError(std::io::Error::last_os_error()));
-                DestroyWindow(hwnd);
-                return result;
+            let registered = register_tray_icon(hwnd, internal_id, &hicon, &attrs.tooltip);
+            if !registered {
+                let os_error = std::io::Error::last_os_error();
+                if taskbar_window_exists() {
```
Comment (anyduck) [inline src/platform_impl/windows/mod.rs]: I scripted restarting `explorer.exe` before tauri app, and quite often (~10 tries) there's `Unspecified error (os error -2147467259)` even though `taskbar_window_exists()` returns true

Maybe it should always be ignored or warned about?

**Review by anyduck — COMMENTED** [review]
This fixed errors on auto start in [loa-logs](https://github.com/snoww/loa-logs) for me.

I also looked at how Qt [implements it](https://github.com/qt/qtbase/blob/6.9.2/src/plugins/platforms/windows/qwindowssystemtrayicon.cpp#L279) in C++, and they don't store whether the tray icon was successfully registered. So we could also just call  `remove_tray_icon` and `register_tray_icon` instead of checking for `userdata.registered`

File: src/platform_impl/windows/mod.rs (hunk 1 above)
Comment (Slinetrac) [reply src/platform_impl/windows/mod.rs]: You're right. Let's just ignore that.

**Comment by Slinetrac** [comment]
> I also looked at how Qt [implements it](https://github.com/qt/qtbase/blob/6.9.2/src/plugins/platforms/windows/qwindowssystemtrayicon.cpp#L279) in C++, and they don't store whether the tray icon was successfully registered.

Thanks for the info! Addressed in https://github.com/tauri-apps/tray-icon/pull/293/changes/ef2e99ac9959571f5a2540023ab2fc914395f805.

File: src/platform_impl/windows/mod.rs [hunk 2]
```diff
@@ -334,7 +336,6 @@ unsafe extern "system" fn tray_proc(
             userdata.tooltip = *tooltip;
         }
         _ if msg == *S_U_TASKBAR_RESTART => {
-            remove_tray_icon(userdata.hwnd, userdata.internal_id);
```
Comment (amrbashir) [inline src/platform_impl/windows/mod.rs:337]: why was this removed? I believe we should keep it.

Comment (Slinetrac) [reply src/platform_impl/windows/mod.rs:337]: Removal is unnecessary: TaskbarCreated indicates Explorer has rebuilt the taskbar and cleared its tray entries. Our HWND/HICON remain valid, so the correct action is to re‑add the icon with NIM_ADD. Deleting first is redundant and can fail noisily—consistent with [Qt’s approach](https://github.com/qt/qtbase/blob/6f0d27d2e4ba5fa6562f738aaaf8eaf98ebf51e7/src/plugins/platforms/windows/qwindowssystemtrayicon.cpp#L279).

Comment (Slinetrac) [reply src/platform_impl/windows/mod.rs:337]: We can also refer to the [Microsoft docs](https://learn.microsoft.com/en-us/windows/win32/shell/taskbar#taskbar-creation-notification):
>  When your taskbar application receives this message, it should assume that any taskbar icons it added have been removed and add them again.

Comment (amrbashir) [reply src/platform_impl/windows/mod.rs:337]: makes sense

**Review by amrbashir — APPROVED** [review]

**Comment by amrbashir** [comment]
Thank you

File: src/platform_impl/windows/mod.rs (hunk 2 above)
Comment (Legend-Master) [reply src/platform_impl/windows/mod.rs:337]: This was added in #145 because without it, the tray icon would get blurrier and blurrier when you change the DPIs, and I am commenting here because I am seeing that behavior back after updating my app

@Slinetrac did you have any real world reasons for the removal? (e.g. it is causing problems) I would like to revert this back if that's not the case

Comment (Slinetrac) [reply src/platform_impl/windows/mod.rs:337]: > did you have any real world reasons for the removal? (e.g. it is causing problems) I would like to revert this back if that's not the case

My bad, no specific reason for the removal—feel free to revert it!
